### ISSUE TITLE
Index columns that are used to create views

### ISSUE THREAD

**Issue by weaverba137** [astro-datalab/digestor#13]
Columns that are used to create views should be indexed.  For example `specobj` is created from `specobjall` with `WHERE scienceprimary=1`.  So `scienceprimary` should be indexed.

**Comment by mjfitzpatrick** [comment]
Created a scienceprimary index on specobjall for sdss_dr12/sdss_dr14/sdss_dr16 on db01/db02/db03

**Comment by weaverba137** [comment]
Thank you for doing this for the *installed* versions, but this ticket is meant for me to update the `digestor` code so that *future* views will always have the necessary indexes.
